In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

In [1]:
import torch
import torchvision
from torch import nn
from torch.autograd import Variable
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.utils import save_image
from torchvision.datasets import MNIST
import os
import pandas as pd
import numpy as np
import random
random.seed(7)

In [2]:
df = pd.read_csv('../input/train.csv', dtype = {'acoustic_data': np.int16, 'time_to_failure': np.float32} ) # float32 is enough :)

In [10]:
ttf = df['time_to_failure'].values
index_start = np.nonzero(np.diff(ttf) > 0)[0] + 1
index_start = np.insert(index_start, 0, 0)
dict_df={}
for i in range(len(index_start)-1):
  df_tmp=df[index_start[i]:index_start[i+1]]
  dict_df["df"+str(i)]=df_tmp

In [11]:
len(dict_df)

16

In [41]:
def randomChoice(l):
    return random.randint(0, l - 1)

150000

In [59]:
def sampler(df_dict):
  k = len(df_dict)
  num=randomChoice(k)
  print(num)
  len_df=len(df_dict['df'+str(num)])
  idx_start=random.randint(0,len_df-149999)
  idx_end=idx_start+150000
  print('Start Index:',idx_start)
  print('End Index:',idx_end)
  sample_x=df_tmp.iloc[idx_start:idx_end]['acoustic_data']
  sample_y=df_tmp.iloc[idx_start:idx_end]['time_to_failure']
  sample_x=np.array(sample_x)
  sample_y=np.array(sample_y)
  return sample_x,sample_y
  

In [71]:
xtrain,ytrain=sampler(dict_df)

6
Start Index: 12495588
End Index: 12645588


In [73]:
xtrain

array([4, 6, 5, ..., 6, 4, 4], dtype=int16)

In [107]:
ytrain

array([6.214397 , 6.214397 , 6.214397 , ..., 6.1749988, 6.1749988,
       6.1749988], dtype=float32)

1500*100

In [72]:
xtrain.shape

(150000,)

In [101]:
xtrainimg=np.zeros((1500,100))
ytrainimg=np.zeros((1500,100))

In [102]:
xtrainimg

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [103]:
for i in range(100):
    for j in range(1500):
        xtrainimg[j][i]=xtrain[1500*i+j]


In [104]:
for i in range(100):
    for j in range(1500):
        ytrainimg[j][i]=ytrain[1500*i+j]

In [105]:
xtrainimg

array([[ 4.,  9.,  4., ...,  1.,  5.,  4.],
       [ 6., 10.,  7., ...,  3.,  5.,  5.],
       [ 5., 12.,  4., ...,  2.,  4.,  2.],
       ...,
       [ 4.,  1.,  0., ...,  4.,  3.,  6.],
       [ 2.,  4.,  3., ...,  6.,  5.,  4.],
       [ 8.,  2.,  6., ...,  5.,  6.,  4.]])

In [109]:
ytrainimg


array([[6.21439695, 6.21329975, 6.21329832, ..., 6.1760993 , 6.17609739,
        6.17609596],
       [6.21439695, 6.21329975, 6.21329832, ..., 6.1760993 , 6.17609739,
        6.17609596],
       [6.21439695, 6.21329975, 6.21329832, ..., 6.1760993 , 6.17609739,
        6.17609596],
       ...,
       [6.21329975, 6.21329832, 6.21329641, ..., 6.17609739, 6.17609596,
        6.17499876],
       [6.21329975, 6.21329832, 6.21329641, ..., 6.17609739, 6.17609596,
        6.17499876],
       [6.21329975, 6.21329832, 6.21329641, ..., 6.17609739, 6.17609596,
        6.17499876]])

Start Index: 39887487
End Index: 40037487

In [191]:
def randomTrainingExample(df_dict):
  k = len(df_dict)
  num=randomChoice(k)
  print(num)
  len_df=len(df_dict['df'+str(num)])
  idx_start=random.randint(0,len_df-149999)
  idx_end=idx_start+150000
  print('Start Index:',idx_start)
  print('End Index:',idx_end)
  df_tmp=df_dict['df'+str(num)]
  sample_x=df_tmp.iloc[idx_start:idx_end]['acoustic_data']
  sample_y=df_tmp.iloc[idx_start:idx_end]['time_to_failure']
  sample_x=np.array(sample_x)
  sample_y=np.array(sample_y)
  xtrain=sample_x
  ytrain=sample_y
  xtrainimg=np.zeros((1500,100))
  ytrainimg=np.zeros((1500,100))
  print(xtrain)
  for i in range(100):
    for j in range(1500):
        xtrainimg[j][i]=xtrain[1500*i+j]
 
  for i in range(100):
    for j in range(1500):
        ytrainimg[j][i]=ytrain[1500*i+j]
   
  return xtrainimg,ytrainimg 
  
    

In [192]:
xtrain,ytrain=randomTrainingExample(dict_df)


8
Start Index: 11656458
End Index: 11806458
[3 3 3 ... 7 9 6]
